### ISSUE TITLE
File Cache gets EOFError

### ISSUE THREAD

**Issue by bill0070** [pallets/cachelib#50] opened 2021-07-08 10:01 UTC
The same bug described with cachlib version 0.1.1 here: "https://github.com/pallets/cachelib/issues/21", seems to appear also in version 0.2.0

I faced the same issue with 0.1.1:

[Tue Jul 06 09:57:39.680042 2021] [wsgi:error] [pid 172159] [client 127.0.0.1:38240]     self._prune()
[Tue Jul 06 09:57:39.680048 2021] [wsgi:error] [pid 172159] [client 127.0.0.1:38240]   File "/lib/python3.6/site-packages/flask_app/cachelib/file.py", line 96, in _prune
[Tue Jul 06 09:57:39.680053 2021] [wsgi:error] [pid 172159] [client 127.0.0.1:38240]     expires = pickle.load(f)
[Tue Jul 06 09:57:39.680059 2021] [wsgi:error] [pid 172159] [client 127.0.0.1:38240] EOFError: Ran out of input

After replacing cachlib with the new version 0.2.0, this error appears again:

[Thu Jul 08 12:41:55.193613 2021] [wsgi:error] [pid 111282] [client 127.0.0.1:51574] self._prune()
[Thu Jul 08 12:41:55.193626 2021] [wsgi:error] [pid 111282] [client 127.0.0.1:51574] File "/lib/python3.6/site-packages/flask_app/cachelib/file.py", line 122, in _prune
[Thu Jul 08 12:41:55.193639 2021] [wsgi:error] [pid 111282] [client 127.0.0.1:51574] self._remove_expired(now)
[Thu Jul 08 12:41:55.193652 2021] [wsgi:error] [pid 111282] [client 127.0.0.1:51574] File "/lib/python3.6/site-packages/flask_app/cachelib/file.py", line 91, in _remove_expired
[Thu Jul 08 12:41:55.193666 2021] [wsgi:error] [pid 111282] [client 127.0.0.1:51574] expires = pickle.load(f)
[Thu Jul 08 12:41:55.193679 2021] [wsgi:error] [pid 111282] [client 127.0.0.1:51574] EOFError: Ran out of input

In both cases, the error is in picke.load(f)

Environment:
- Python version: python3.6

**Comment by northernSage** [comment] 2021-07-08 16:44
Thanks for letting us know. I'll close this to avoid duplicates and reopen #21 since most of the discussion regarding the issue is there.

**Closed by northernSage** 2021-07-08 16:44 UTC
